"""Server-side report localization (Phase 5).

Report locale is chosen per report, independent of the UI language. English is the
default/fallback. User-entered free text (incident notes, corrective actions) is
NEVER auto-translated.
"""

from __future__ import annotations

_MONTHS = {
    "en": [
        "", "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
    ],
    "de": [
        "", "Januar", "Februar", "März", "April", "Mai", "Juni",
        "Juli", "August", "September", "Oktober", "November", "Dezember",
    ],
}

_LABELS: dict[str, dict[str, str]] = {
    "en": {
        "report_title_default": "HACCP Temperature Report",
        "period": "Reporting period",
        "report_id": "Report ID",
        "generated": "Generated",
        "timezone": "Timezone",
        "organization": "Organization",
        "site": "Site",
        "overall_status": "Overall status",
        "unit": "Storage unit",
        "type": "Type / profile",
        "range": "Permitted range",
        "min": "Min",
        "max": "Max",
        "avg": "Average",
        "coverage": "Data coverage",
        "unavailable": "Unavailable",
        "incidents": "Incidents",
        "longest_incident": "Longest incident",
        "time_above": "Time above limit",
        "time_below": "Time below limit",
        "defrost": "Defrost",
        "defrost_cycles": "Defrost cycles",
        "typical_duration": "Typical duration",
        "max_duration": "Max duration",
        "recovery": "Recovery",
        "abnormal": "Abnormal",
        "data_quality": "Data quality",
        "incomplete_warning": (
            "Data is incomplete for this period — not a compliance statement."
        ),
        "missing_entity": "No sensor data recorded.",
        "configured_limits": "Configured safety limits",
        "operational_note": (
            "Operational defrost characteristics are learned and are not legal/HACCP limits."
        ),
        "review": "Review & signature",
        "prepared_by": "Prepared by",
        "date": "Date",
        "signature": "Signature",
        "page": "Page",
        "of": "of",
        "none": "None",
        "incident_type": "Type",
        "incident_state": "State",
        "incident_start": "Start",
        "incident_end": "End",
        "incident_duration": "Duration",
        "incident_extreme": "Extreme",
        "corrective_action": "Corrective action",
        "no_incidents": "No incidents in this period.",
        "chart_unit": "°C",
        "summary_units": "Storage units",
        "summary_incidents": "Total incidents",
        "report_period": "Reporting period",
        "created_at": "Created",
        "overview_title": "OVERALL SUMMARY",
        "summary_table_title": "SUMMARY OF ALL STORAGE UNITS",
        "charts_title": "TEMPERATURE TREND — MONTHLY OVERVIEW",
        "details_title": "STORAGE-UNIT DETAILS",
        "incidents_title": "INCIDENTS (SUMMARY)",
        "monitored": "monitored storage units",
        "coverage_total": "overall data coverage",
        "incomplete_from": "Incomplete data — measurements available only from {date}",
        "confirmed_deviations": "confirmed deviations",
        "open_incidents": "open incidents",
        "assessment": "OVERALL ASSESSMENT",
        "verdict_ok": "Complete, no deviations",
        "verdict_documented": "Complete with documented deviations",
        "verdict_open": "Open incidents present",
        "verdict_incomplete": "Incomplete data",
        "permitted_range": "Permitted range",
        "outside_range": "Outside range",
        "outside_short": "Outside",
        "status": "Status",
        "status_reviewed": "Reviewed",
        "status_ok_unit": "OK",
        "status_open": "Open incident",
        "status_incomplete": "Incomplete",
        "chilled_group": "Chilled units (positive temperature)",
        "frozen_group": "Frozen units (deep-freeze)",
        "band_deviation": "Deviation (outside range)",
        "band_gap": "Data gap / no values",
        "band_defrost": "Defrost (if configured)",
        "upper_limit": "Upper limit",
        "lower_limit": "Lower limit",
        "inc_no": "No.",
        "inc_unit": "Storage unit",
        "inc_start": "Start",
        "inc_duration": "Duration",
        "inc_extreme": "Extreme",
        "inc_cause": "Cause",
        "inc_action": "Corrective action",
        "data_quality_title": "DATA QUALITY",
        "dq_ok": "No critical data gaps. Sensors were largely available during the period.",
        "dq_incomplete": "Data is incomplete for this period — not a compliance statement.",
        "approval_title": "APPROVAL",
        "reviewed_by": "Reviewed by",
        "comment": "Comment",
        "disclaimer_default": (
            "This report is generated automatically and documents temperature data in "
            "support of HACCP documentation. It does not replace operational checks, "
            "measurements or legal requirements."
        ),
    },
    "de": {
        "report_title_default": "HACCP-Temperaturbericht",
        "period": "Berichtszeitraum",
        "report_id": "Berichts-ID",
        "generated": "Erstellt",
        "timezone": "Zeitzone",
        "organization": "Organisation",
        "site": "Standort",
        "overall_status": "Gesamtstatus",
        "unit": "Lagereinheit",
        "type": "Typ / Profil",
        "range": "Zulässiger Bereich",
        "min": "Min",
        "max": "Max",
        "avg": "Mittel",
        "coverage": "Datenabdeckung",
        "unavailable": "Nicht verfügbar",
        "incidents": "Vorfälle",
        "longest_incident": "Längster Vorfall",
        "time_above": "Zeit über Grenze",
        "time_below": "Zeit unter Grenze",
        "defrost": "Abtauen",
        "defrost_cycles": "Abtauzyklen",
        "typical_duration": "Typische Dauer",
        "max_duration": "Max. Dauer",
        "recovery": "Erholung",
        "abnormal": "Auffällig",
        "data_quality": "Datenqualität",
        "incomplete_warning": (
            "Daten für diesen Zeitraum unvollständig — keine Konformitätsaussage."
        ),
        "missing_entity": "Keine Sensordaten aufgezeichnet.",
        "configured_limits": "Konfigurierte Sicherheitsgrenzen",
        "operational_note": (
            "Betriebliche Abtauwerte sind gelernt und keine rechtlichen/HACCP-Grenzen."
        ),
        "review": "Prüfung & Unterschrift",
        "prepared_by": "Erstellt von",
        "date": "Datum",
        "signature": "Unterschrift",
        "page": "Seite",
        "of": "von",
        "none": "Keine",
        "incident_type": "Typ",
        "incident_state": "Status",
        "incident_start": "Beginn",
        "incident_end": "Ende",
        "incident_duration": "Dauer",
        "incident_extreme": "Extremwert",
        "corrective_action": "Korrekturmaßnahme",
        "no_incidents": "Keine Vorfälle in diesem Zeitraum.",
        "chart_unit": "°C",
        "summary_units": "Lagereinheiten",
        "summary_incidents": "Vorfälle gesamt",
        "report_period": "Berichtszeitraum",
        "created_at": "Erstellt am",
        "overview_title": "GESAMTÜBERSICHT",
        "summary_table_title": "ZUSAMMENFASSUNG ALLER KÜHLBEREICHE",
        "charts_title": "TEMPERATURVERLAUF — MONATSÜBERSICHT",
        "details_title": "DETAILS JE KÜHLBEREICH",
        "incidents_title": "VORFÄLLE (ZUSAMMENFASSUNG)",
        "monitored": "Kühlbereiche überwacht",
        "coverage_total": "Datenabdeckung gesamt",
        "incomplete_from": "Unvollständige Daten — Messwerte erst ab {date}",
        "confirmed_deviations": "bestätigte Abweichungen",
        "open_incidents": "offene Vorfälle",
        "assessment": "BEWERTUNG GESAMT",
        "verdict_ok": "Vollständig ohne Abweichungen",
        "verdict_documented": "Vollständig mit dokumentierten Abweichungen",
        "verdict_open": "Offene Vorfälle vorhanden",
        "verdict_incomplete": "Unvollständige Daten",
        "permitted_range": "Sollbereich",
        "outside_range": "Außerhalb des Bereichs",
        "outside_short": "Außerhalb",
        "status": "Status",
        "status_reviewed": "Geprüft",
        "status_ok_unit": "OK",
        "status_open": "Offener Vorfall",
        "status_incomplete": "Unvollständig",
        "chilled_group": "Kühlbereiche (positiver Temperaturbereich)",
        "frozen_group": "Kühlbereich (Tiefkühlung)",
        "band_deviation": "Abweichung (außerhalb Grenzbereich)",
        "band_gap": "Datenlücke / keine Werte",
        "band_defrost": "Abtauung (sofern konfiguriert)",
        "upper_limit": "Oberer Grenzwert",
        "lower_limit": "Unterer Grenzwert",
        "inc_no": "Nr.",
        "inc_unit": "Kühlbereich",
        "inc_start": "Beginn",
        "inc_duration": "Dauer",
        "inc_extreme": "Extremwert",
        "inc_cause": "Ursache",
        "inc_action": "Maßnahme",
        "data_quality_title": "DATENQUALITÄT",
        "dq_ok": (
            "Keine kritischen Datenlücken. Alle Sensoren waren im Berichtszeitraum "
            "überwiegend verfügbar."
        ),
        "dq_incomplete": "Daten für diesen Zeitraum unvollständig — keine Konformitätsaussage.",
        "approval_title": "FREIGABE",
        "reviewed_by": "Geprüft durch",
        "comment": "Bemerkung",
        "disclaimer_default": (
            "Dieser Bericht wurde automatisch erstellt und dokumentiert Temperaturdaten zur "
            "Unterstützung der HACCP-Dokumentation. Er ersetzt keine betrieblichen Kontrollen, "
            "Messungen oder gesetzlichen Anforderungen."
        ),
    },
}


def month_name(month: int, locale: str) -> str:
    table = _MONTHS.get(locale, _MONTHS["en"])
    if 1 <= month <= 12:
        return table[month]
    return str(month)


def labels(locale: str) -> dict[str, str]:
    return _LABELS.get(locale, _LABELS["en"])
